name: lakefusion-app

# Allow Authorization header to pass through for API routes
auth:
  unauthenticated_paths:
    - /api/*

command:
  - "uvicorn"
  - "app.main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

resources:
  - name: lakefusion-db
    type: postgres
    database: lakefusion_transactional_db
    permission: CAN_CONNECT_AND_CREATE

env:
  - name: SERVICE_NAME
    value: LakeFusionApp
  - name: DB_TYPE
    value: "lakebase"
  - name: DEPLOYMENT_ENV
    value: "production"
  - name: DB_POOL_SIZE
    value: "10"
  - name: DB_MAX_OVERFLOW
    value: "20"
  - name: DB_POOL_TIMEOUT
    value: "60"
  - name: DB_POOL_RECYCLE
    value: "1200"
  - name: RUN_DBX_PIPELINE_ARTIFACTS_IMPORT
    value: "True"
  - name: DATA_DB_TYPE
    value: "lakebase"
  - name: DATA_DATABRICKS_DATABASE_INSTANCE
    value: "lakefusion-db-pim"
  - name: DATA_DB_SEARCH_PATH
    value: "gold"
  - name: DATABRICKS_OIDC_CLIENT_ID
    valueFrom: DATABRICKS_OIDC_CLIENT_ID
  - name: DATABRICKS_OIDC_CLIENT_SECRET
    valueFrom: DATABRICKS_OIDC_CLIENT_SECRET
