"""init

Revision ID: 0ea5a919a9ee
Revises: 
Create Date: 2025-08-22 18:25:44.010062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0ea5a919a9ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    conn = op.get_bind()
    dialect = conn.dialect.name

    if dialect == 'mysql':
        conn.execute(sa.text("""
            DELETE me
            FROM model_experiments me
            LEFT JOIN entity e ON me.entity_id = e.id
            WHERE e.id IS NULL AND me.entity_id IS NOT NULL;
        """))
        conn.execute(sa.text("""
            DELETE mmj
            FROM match_maven_job mmj
            LEFT JOIN entity e ON mmj.entity_id = e.id
            WHERE e.id IS NULL AND mmj.entity_id IS NOT NULL;
        """))
        conn.execute(sa.text("""
            DELETE mmj
            FROM match_maven_job mmj
            LEFT JOIN model_experiments me ON mmj.modelid = me.id
            WHERE me.id IS NULL AND mmj.modelid IS NOT NULL;
        """))
        conn.execute(sa.text("""
            DELETE ih1
            FROM integration_hub ih1
            JOIN integration_hub ih2
              ON ih1.modelid = ih2.modelid
             AND ih1.entity_id = ih2.entity_id
             AND ih1.id > ih2.id;
        """))
    else:
        conn.execute(sa.text("""
            DELETE FROM model_experiments
            USING entity
            WHERE model_experiments.entity_id = entity.id
              AND entity.id IS NULL AND model_experiments.entity_id IS NOT NULL;
        """))
        conn.execute(sa.text("""
            DELETE FROM match_maven_job
            USING entity
            WHERE match_maven_job.entity_id = entity.id
              AND entity.id IS NULL AND match_maven_job.entity_id IS NOT NULL;
        """))
        conn.execute(sa.text("""
            DELETE FROM match_maven_job
            USING model_experiments
            WHERE match_maven_job.modelid = model_experiments.id
              AND model_experiments.id IS NULL AND match_maven_job.modelid IS NOT NULL;
        """))
        conn.execute(sa.text("""
            DELETE FROM integration_hub ih1
            USING integration_hub ih2
            WHERE ih1.modelid = ih2.modelid
              AND ih1.entity_id = ih2.entity_id
              AND ih1.id > ih2.id;
        """))
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed op.create_table('audit_logs') and op.drop_table('feature_flags')
    # All tables are managed by SQLAlchemy models via Base.metadata.create_all()
    # Migrations should only handle schema alterations, not table creation/deletion
    op.drop_index('name', table_name='business_glossary_categories')
    op.create_unique_constraint(op.f('uq_business_glossary_categories_name'), 'business_glossary_categories', ['name'])
    op.alter_column('entitydatasetmapping', 'attributes',
               existing_type=sa.JSON(),
               nullable=False)
    op.create_unique_constraint('uix_modelid_entityid', 'integration_hub', ['modelid', 'entity_id'])
    op.drop_constraint('integration_hub_model_experiments_FK', 'integration_hub', type_='foreignkey')
    op.create_foreign_key(op.f('fk_integration_hub_modelid_model_experiments'), 'integration_hub', 'model_experiments', ['modelid'], ['id'])
    op.alter_column('match_maven_job', 'existing_cluster_id',
               existing_type=sa.Integer(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_match_maven_job_modelid_model_experiments'), 'match_maven_job', 'model_experiments', ['modelid'], ['id'])
    op.create_foreign_key(op.f('fk_match_maven_job_entity_id_entity'), 'match_maven_job', 'entity', ['entity_id'], ['id'])
    op.alter_column('model_experiments', 'vs_endpoint',
               existing_type=sa.String(255),
               nullable=False,
               existing_server_default=sa.text("'lakefusion_vs_endpoint'"))
    op.create_foreign_key(op.f('fk_model_experiments_entity_id_entity'), 'model_experiments', 'entity', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_model_experiments_entity_id_entity'), 'model_experiments', type_='foreignkey')
    op.alter_column('model_experiments', 'vs_endpoint',
               existing_type=sa.String(255),
               nullable=True,
               existing_server_default=sa.text("'lakefusion_vs_endpoint'"))
    op.drop_constraint(op.f('fk_match_maven_job_entity_id_entity'), 'match_maven_job', type_='foreignkey')
    op.drop_constraint(op.f('fk_match_maven_job_modelid_model_experiments'), 'match_maven_job', type_='foreignkey')
    op.alter_column('match_maven_job', 'existing_cluster_id',
               existing_type=sa.String(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_integration_hub_modelid_model_experiments'), 'integration_hub', type_='foreignkey')
    op.create_foreign_key('integration_hub_model_experiments_FK', 'integration_hub', 'model_experiments', ['modelid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint('uix_modelid_entityid', 'integration_hub', type_='unique')
    op.alter_column('entitydatasetmapping', 'attributes',
               existing_type=sa.JSON(),
               nullable=True)
    op.drop_constraint(op.f('uq_business_glossary_categories_name'), 'business_glossary_categories', type_='unique')
    op.create_index('name', 'business_glossary_categories', ['name'], unique=True)
    # NOTE: Removed feature_flags creation and audit_logs drop
    # Tables are managed by SQLAlchemy models via Base.metadata.create_all()
    # ### end Alembic commands ###
