"""match_maven_historical_jobs_support

Revision ID: 0f387b4197ef
Revises: 4f3b398e6460
Create Date: 2025-10-29 16:55:53.585438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f387b4197ef'
down_revision: Union[str, None] = '4f3b398e6460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_maven_job', sa.Column('historical_jobs', mysql.JSON(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_maven_job', 'historical_jobs')
    # ### end Alembic commands ###
