"""max_potential_matches_field

Revision ID: 5e37b3b20a8b
Revises: ea515bd215a1
Create Date: 2025-09-09 16:41:12.254454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e37b3b20a8b'
down_revision: Union[str, None] = 'ea515bd215a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_experiments', sa.Column('max_potential_matches', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_experiments', 'max_potential_matches')
    # ### end Alembic commands ###
