"""validation function changes

Revision ID: 6ad578c4345f
Revises: 5e37b3b20a8b
Create Date: 2025-09-12 19:28:44.399866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad578c4345f'
down_revision: Union[str, None] = '5e37b3b20a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validationfunctions', sa.Column('function_definition', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validationfunctions', 'function_definition')
    # ### end Alembic commands ###
