""" updated integration hub with version column

Revision ID: b53b5143972d
Revises: b6bda54882de
Create Date: 2025-12-01 20:45:41.677112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision: str = 'b53b5143972d'
down_revision: Union[str, None] = 'b6bda54882de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_hub', sa.Column('version', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_hub', 'version')
    # ### end Alembic commands ###
