"""enable validation function warning feature flag

Revision ID: b6bda54882de
Revises: f6fb868870a0
Create Date: 2025-11-25 14:53:16.694304

"""
from typing import Sequence, Union
from datetime import datetime
from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql import table, column
from sqlalchemy import String, Enum, Text, DateTime
from datetime import datetime
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = 'b6bda54882de'
down_revision: Union[str, None] = 'f6fb868870a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    feature_flags = table(
        'feature_flags',
        column('name', String),
        column('status', Enum),
        column('description', Text),
        column('owner_team', String),
        column('created_at', DateTime),
        column('updated_at', DateTime),
        column('expires_at', DateTime),
    )

    op.bulk_insert(
        feature_flags,
        [
            {
                "name": "ENABLE_VALIDATION_FUNCTION_WARNING_FEATURE",
                "status": "INACTIVE",
                "description": "Enables validation function warning feature in the application",
                "owner_team": "LakeFusion",
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow(),
                "expires_at": None,
            }
        ]
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM feature_flags WHERE name='ENABLE_VALIDATION_FUNCTION_WARNING_FEATURE';"
    )
    # ### end Alembic commands ###
