"""update feature flag status

Revision ID: ce1c99df9f70
Revises: b53b5143972d
Create Date: 2025-12-09 12:39:53.878644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ce1c99df9f70'
down_revision: Union[str, None] = 'b53b5143972d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        UPDATE feature_flags
        SET status = 'ACTIVE'
        WHERE name = 'ENABLE_BASE_PROMPT_MANAGEMENT_FEATURE';
    """)
    op.execute("""
        UPDATE feature_flags
        SET status = 'ACTIVE'
        WHERE name = 'MDM_RESTRUCTURING';
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
        UPDATE feature_flags
        SET status = 'INACTIVE'
        WHERE name = 'ENABLE_BASE_PROMPT_MANAGEMENT_FEATURE';
    """)
    op.execute("""
        UPDATE feature_flags
        SET status = 'INACTIVE'
        WHERE name = 'MDM_RESTRUCTURING';
    """)
   
    # ### end Alembic commands ###
