"""integrtion hub changes

Revision ID: ea515bd215a1
Revises: 0ea5a919a9ee
Create Date: 2025-09-04 17:56:15.596700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea515bd215a1'
down_revision: Union[str, None] = '0ea5a919a9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integration_hub', 'golden_deduplication_quartz_cron_expression',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=45),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integration_hub', 'golden_deduplication_quartz_cron_expression',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
