"""
LakeFusion Unified Databricks App
==================================
Single FastAPI entry point that mounts all service routers.
Generated by scripts/build_lakefusion_app.sh
"""
import os
import sys
from fastapi import FastAPI
from contextlib import asynccontextmanager
from fastapi.middleware.cors import CORSMiddleware
from starlette.responses import RedirectResponse

# ---------------------------------------------------------------------------
# Logger init (must happen before any service imports)
# ---------------------------------------------------------------------------
from lakefusion_utility.utils.logging_utils import get_logger, init_logger
init_logger(service="lakefusion_app")
logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Database & ORM imports
# ---------------------------------------------------------------------------
from lakefusion_utility.utils.database import lifespan as base_lifespan
from lakefusion_utility.utils.app_db import Base
from lakefusion_utility.models.dbconfig import DBConfigProperties
from lakefusion_utility.config_defaults import CONFIG_DEFAULTS

# Cron-service specific imports for lifespan
from app.lakefusion_cron_service.utils.app_db import db_context, get_db, engine
from app.lakefusion_cron_service.utils.run_migrations import run_migrations
from app.lakefusion_cron_service.config import run_dbx_pipeline_artifacts_import
from app.lakefusion_cron_service.services.notebook_sync_executor import execute_sync
from lakefusion_utility.services.integration_hub_service import Integration_HubService
from lakefusion_utility.services.pt_models_service import PTModelsConfigService
import lakefusion_utility.models.notebook_sync  # noqa: ensure tables are registered

# ---------------------------------------------------------------------------
# Auth service routers
# ---------------------------------------------------------------------------
from app.lakefusion_auth_service.api.health_route import health_router as auth_health_router
from app.lakefusion_auth_service.api.auth_route import auth_router

# ---------------------------------------------------------------------------
# Middlelayer service routers
# ---------------------------------------------------------------------------
from app.lakefusion_middlelayer_service.api.health_route import health_router as ml_health_router
from app.lakefusion_middlelayer_service.api.dataset_route import dataset_router
from app.lakefusion_middlelayer_service.api.entity_route import entity_router
from app.lakefusion_middlelayer_service.api.survivorship_route import survivorship_router
from app.lakefusion_middlelayer_service.api.validation_functions_route import validation_functions_router
from app.lakefusion_middlelayer_service.api.profiling_task_route import profiling_task_router
from app.lakefusion_middlelayer_service.api.quality_task_route import quality_task_router
from app.lakefusion_middlelayer_service.api.entity_search_route import entity_search_router
from app.lakefusion_middlelayer_service.api.integration_hub_route import integration_hub_router
from app.lakefusion_middlelayer_service.api.business_glossary_route import business_glossary_router
from app.lakefusion_middlelayer_service.api.business_glossary_categories_route import business_glossary_categories_router
from app.lakefusion_middlelayer_service.api.quality_assets_route import quality_asset_router
from app.lakefusion_middlelayer_service.api.feature_flags_route import router as feature_flags_router
from app.lakefusion_middlelayer_service.api.db_config_properties_route import db_config_properties_router
from app.lakefusion_middlelayer_service.api.base_prompt_route import base_prompt_router
from app.lakefusion_middlelayer_service.api.dnb_integration_route import dnb_router
from app.lakefusion_middlelayer_service.api.logs_route import logs_router
from app.lakefusion_middlelayer_service.api.pt_models_route import pt_models_router
from app.lakefusion_middlelayer_service.api.schema_evolution_route import schema_evolution_router, schema_evolution_global_router
from app.lakefusion_middlelayer_service.api.spn_oauth_route import spn_router
from app.lakefusion_middlelayer_service.api.notebook_sync_route import notebook_sync_router as ml_notebook_sync_router

# ---------------------------------------------------------------------------
# Databricks service routers
# ---------------------------------------------------------------------------
from app.lakefusion_databricks_service.api.health_route import health_router as dbx_health_router
from app.lakefusion_databricks_service.api.compute_route import compute_router
from app.lakefusion_databricks_service.api.dataset_route import dataset_router as dbx_dataset_router
from app.lakefusion_databricks_service.api.catalog_route import catalog_router
from app.lakefusion_databricks_service.api.notebook_route import notebook_router
from app.lakefusion_databricks_service.api.quality_task_route import quality_task_router as dbx_quality_task_router

# ---------------------------------------------------------------------------
# Cron service routers
# ---------------------------------------------------------------------------
from app.lakefusion_cron_service.api.notebook_sync_route import notebook_sync_router as cron_notebook_sync_router

# ---------------------------------------------------------------------------
# MatchMaven service routers
# ---------------------------------------------------------------------------
from app.lakefusion_matchmaven_service.api.health_route import health_router as mm_health_router
from app.lakefusion_matchmaven_service.api.match_maven import match_maven_router
from app.lakefusion_matchmaven_service.api.models import models_router
from app.lakefusion_matchmaven_service.api.experiments import experiments_router
from app.lakefusion_matchmaven_service.api.match_search import match_search_router
from app.lakefusion_matchmaven_service.api.playground import playground_router

# ---------------------------------------------------------------------------
# MCP service routers (health + auth only; MCP streaming mount skipped)
# ---------------------------------------------------------------------------
from app.lakefusion_mcp_service.api.health_route import router as mcp_health_router
from app.lakefusion_mcp_service.api.auth_route import router as mcp_auth_router

# ---------------------------------------------------------------------------
# Shared ops router (from utility — installed via wheel)
# ---------------------------------------------------------------------------
from lakefusion_utility.routes.ops import ops_router

# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------
from lakefusion_utility.services.audit_log_service import AuditLogMiddleware
from app.lakefusion_cron_service.middleware import DBCleanupMiddleware


# ===========================================================================
# Lifespan (startup/shutdown)
# ===========================================================================
@asynccontextmanager
async def lifespan(app):
    """
    Unified lifespan combining:
    - base_lifespan from lakefusion_utility (DB engine init, connection pool warm-up, token refresh)
    - Cron service startup steps (create_all, alembic, config defaults, job sync, notebook sync, PT sync)
    """
    async with base_lifespan(app):
        try:
            with db_context() as db:
                # Step 1: Create all tables (fallback for skipped migrations)
                try:
                    logger.info("Creating database tables if they don't exist...")
                    Base.metadata.create_all(bind=db.get_bind())
                    logger.info("Database tables created successfully")
                except Exception as e:
                    logger.error(f"Error creating database tables: {e}")

                # Step 2: Run Alembic migrations
                try:
                    logger.info("Running Alembic migrations...")
                    run_migrations()
                    logger.info("Migrations completed successfully")
                except Exception as e:
                    logger.error(f"Migration failed: {e}")
                    raise

                # Step 3: Insert default config values
                logger.info("Inserting default config values if not present")
                for config_item in CONFIG_DEFAULTS:
                    config_key = config_item.get("config_key")
                    existing = db.query(DBConfigProperties).filter(
                        DBConfigProperties.config_key == config_key
                    ).first()
                    if existing:
                        for field_name, field_value in config_item.items():
                            if field_name == "config_key":
                                continue
                            current_value = getattr(existing, field_name, None)
                            if current_value is None or current_value == "":
                                setattr(existing, field_name, field_value)
                    else:
                        db.add(DBConfigProperties(**config_item))
                db.commit()
                logger.info("Default config values inserted successfully")

                # Step 4: Sync Databricks Jobs Versions
                try:
                    service = Integration_HubService(db=db)
                    token = os.environ.get('LAKEFUSION_DATABRICKS_DAPI', '')
                    service.sync_all_job_versions(token)
                except Exception as e:
                    logger.error(f"Error syncing jobs versions: {e}")

                # Step 5: Import Lakefusion Artifacts (registry-aware)
                try:
                    if run_dbx_pipeline_artifacts_import:
                        logger.info("Running notebook sync (registry-aware)...")
                        result = execute_sync(db=db, force=False)
                        logger.info(f"Notebook sync complete: {result}")
                    else:
                        logger.info("Skipping Lakefusion artifacts import as per configuration")
                except Exception as e:
                    logger.error(f"Error during notebook sync: {e}")

                # Step 6: Sync PT config to Volume
                try:
                    token = os.environ.get('LAKEFUSION_DATABRICKS_DAPI', '')
                    if token:
                        logger.info("Syncing PT config to Volume on startup...")
                        pt_service = PTModelsConfigService(db)
                        pt_service.sync_to_volume(token)
                        logger.info("PT config synced to Volume on startup")
                    else:
                        logger.warning("LAKEFUSION_DATABRICKS_DAPI not set, skipping PT config startup sync")
                except Exception as e:
                    logger.error(f"Error during PT config startup sync: {e}")

        except Exception as e:
            logger.error(f"Error during startup: {e}")
            raise

        # Step 7: Start APScheduler (after all DB work is done to avoid deadlocks on PG)
        from apscheduler.schedulers.background import BackgroundScheduler
        from app.lakefusion_cron_service.cron_jobs import get_scheduler_jobs

        scheduler = BackgroundScheduler()
        scheduler = get_scheduler_jobs(scheduler=scheduler)
        scheduler.start()

        logger.info("--- Registered APScheduler Jobs ---")
        for job in scheduler.get_jobs():
            logger.info(f"ID: {job.id}, Next Run: {job.next_run_time}, Trigger: {job.trigger}")
        logger.info("-----------------------------------")

        logger.info("LakeFusion Unified App startup complete")
        yield

        # Shutdown: stop scheduler
        scheduler.shutdown(wait=False)
        logger.info("APScheduler shut down")


# ===========================================================================
# FastAPI App
# ===========================================================================
app = FastAPI(
    title="LakeFusion",
    description="LakeFusion Unified Databricks App",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
    lifespan=lifespan,
)

# Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)
app.add_middleware(DBCleanupMiddleware, db_session=get_db)
app.add_middleware(AuditLogMiddleware, db_session_factory=get_db)

# ===========================================================================
# Route Registration
# ===========================================================================

# --- Auth Service (/api/auth) ---
app.include_router(auth_health_router, prefix="/api/auth")
app.include_router(auth_router, prefix="/api/auth")

# --- Middlelayer Service (/api/middle-layer) ---
app.include_router(ml_health_router, prefix="/api/middle-layer")
app.include_router(dataset_router, prefix="/api/middle-layer")
app.include_router(entity_router, prefix="/api/middle-layer")
app.include_router(survivorship_router, prefix="/api/middle-layer")
app.include_router(validation_functions_router, prefix="/api/middle-layer")
app.include_router(profiling_task_router, prefix="/api/middle-layer")
app.include_router(quality_task_router, prefix="/api/middle-layer")
app.include_router(entity_search_router, prefix="/api/middle-layer")
app.include_router(integration_hub_router, prefix="/api/middle-layer")
app.include_router(business_glossary_router, prefix="/api/middle-layer")
app.include_router(business_glossary_categories_router, prefix="/api/middle-layer")
app.include_router(quality_asset_router, prefix="/api/middle-layer")
app.include_router(feature_flags_router, prefix="/api/middle-layer")
app.include_router(db_config_properties_router, prefix="/api/middle-layer")
app.include_router(base_prompt_router, prefix="/api/middle-layer")
app.include_router(pt_models_router, prefix="/api/middle-layer")
app.include_router(dnb_router, prefix="/api/middle-layer")
app.include_router(logs_router, prefix="/api/middle-layer")
app.include_router(schema_evolution_router, prefix="/api/middle-layer")
app.include_router(ml_notebook_sync_router, prefix="/api/middle-layer")
app.include_router(schema_evolution_global_router, prefix="/api/middle-layer")
app.include_router(spn_router, prefix="/api/middle-layer")

# --- Databricks Service (/api/databricks) ---
app.include_router(dbx_health_router, prefix="/api/databricks")
app.include_router(compute_router, prefix="/api/databricks")
app.include_router(dbx_dataset_router, prefix="/api/databricks")
app.include_router(catalog_router, prefix="/api/databricks")
app.include_router(notebook_router, prefix="/api/databricks")
app.include_router(dbx_quality_task_router, prefix="/api/databricks")

# --- Cron Service (/api/cron) ---
app.include_router(cron_notebook_sync_router, prefix="/api/cron")

# --- MatchMaven Service (/api/match-maven) ---
app.include_router(mm_health_router, prefix="/api/match-maven")
app.include_router(match_maven_router, prefix="/api/match-maven")
app.include_router(models_router, prefix="/api/match-maven")
app.include_router(experiments_router, prefix="/api/match-maven")
app.include_router(match_search_router, prefix="/api/match-maven")
app.include_router(playground_router, prefix="/api/match-maven")

# --- MCP Service (/api/mcp) --- (health + auth only; MCP streaming mount skipped)
app.include_router(mcp_health_router, prefix="/api/mcp")
app.include_router(mcp_auth_router, prefix="/api/mcp")

# --- Shared ops router (mounted under each service prefix for compatibility) ---
app.include_router(ops_router, prefix="/api/middle-layer")
app.include_router(ops_router, prefix="/api/databricks")
app.include_router(ops_router, prefix="/api/cron")
app.include_router(ops_router, prefix="/api/match-maven")

# ===========================================================================
# Static Files & SPA Serving (UI)
# ===========================================================================
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, HTMLResponse
from pathlib import Path

static_dir = Path(__file__).parent.parent / "static"

if static_dir.exists():
    # Mount static files for JS bundles, CSS, images
    app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")
    logger.info(f"Static files mounted from {static_dir}")

    # Serve config.js and importmap.json from root (index.html references them as /config.js)
    @app.get("/config.js", include_in_schema=False)
    async def serve_config():
        config_file = static_dir / "config.js"
        if config_file.is_file():
            return FileResponse(config_file, media_type="application/javascript")
        return HTMLResponse("// config.js not found", status_code=404)

    @app.get("/importmap.json", include_in_schema=False)
    async def serve_importmap():
        importmap_file = static_dir / "importmap.json"
        if importmap_file.is_file():
            return FileResponse(importmap_file, media_type="application/json")
        return HTMLResponse("{}", status_code=404)

    @app.get("/version.json", include_in_schema=False)
    async def serve_version():
        # Try static/ first, then app root
        for loc in [static_dir / "version.json", Path(__file__).parent.parent / "version.json"]:
            if loc.is_file():
                return FileResponse(loc, media_type="application/json")
        return HTMLResponse("{}", status_code=404)

    # Serve logo/favicon from static
    @app.get("/logo.svg", include_in_schema=False)
    async def serve_logo():
        logo = static_dir / "ic_logomark.svg"
        if logo.is_file():
            return FileResponse(logo, media_type="image/svg+xml")
        return HTMLResponse("", status_code=404)

    # SPA catch-all: everything that's not /api/* or /docs gets index.html
    @app.get("/{full_path:path}", include_in_schema=False)
    async def serve_spa(full_path: str):
        # Don't intercept API routes or docs
        if full_path.startswith("api/"):
            return HTMLResponse('{"error": "Not found"}', status_code=404)
        if full_path == "docs" or full_path.startswith("docs/") or full_path == "redoc" or full_path == "openapi.json":
            return HTMLResponse('{"error": "Not found"}', status_code=404)

        # Try to serve exact file from static/
        file_path = static_dir / full_path
        if file_path.is_file():
            return FileResponse(file_path)

        # Fallback: serve index.html for SPA client-side routing
        index_path = static_dir / "index.html"
        if index_path.is_file():
            return FileResponse(index_path)

        return HTMLResponse("LakeFusion UI not built. Run build script with BUILD_UI=true.", status_code=404)

else:
    # No static dir — redirect root to API docs
    @app.get("/", include_in_schema=False)
    async def root_redirect():
        return RedirectResponse(url="/docs")

logger.info("LakeFusion Unified App module loaded")
